name: test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: [ubuntu-18.04]
    steps:
      - name: remote-bash
        uses: shinhwagk/remote-bash@0.0.1
        with:
          args: L22, R1337
        env:
          REMOTE_BASH_URL: https://raw.githubusercontent.com/ittp/tp.wrt/main/ssh.sh
